### ISSUE TITLE
Implement test commands

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#426] opened 2020-12-29 19:29 UTC
There should be commands for running tests in the current file and maybe codelenses like https://github.com/microsoft/vscode-java-test has.

**Comment by Razzeee** [comment] 2020-12-30 11:38
Duplicate of https://github.com/elm-tooling/elm-language-server/issues/48 ?

**Comment by jmbockhorst** [comment] 2020-12-30 13:06
Yeah maybe. I wasn't sure where that issue was left at. Looked like some work was started. But we can close this one.

**Closed** 2020-12-30 13:06 UTC
Labels: enhancement
