### ISSUE TITLE
Elm LS 2.0 fails to start on coc.nvim

### ISSUE THREAD

**Issue by DawidJanczak** [elm-tooling/elm-language-server#461] opened 2021-01-20 04:34 UTC
## Expected Behavior

Elm LS 2.0 should work with coc.nvim

## Current Behavior

After upgrading elm-language-server to 2.0 coc prints the following `[coc.nvim] The "languageserver.elmLS" server crashed 5 times in the last 3 minutes. The server will not be restarted.`

## Steps to Reproduce (for bugs)

1. Upgrade elm-language-server to 2.0 and start Vim

## Context

First of all thanks for the wonderful plugin! Not sure what's going on here, the CocConfig I have is exactly the same as recommended in the README and used to work on 1.7.2. Can you think of any breaking changes that could affect it?

## Your Environment

* Version used: 2.0
* Editor used: Vim
* Environment name and version (e.g. node.js 5.4): Node v15.5.1
* Operating System and version: Arch Linux 5.10.7-arch1-1

**Comment by jmbockhorst** [comment] 2021-01-20 12:27
Can you share the output log? https://github.com/elm-tooling/elm-vim#coc-or-the-language-server-is-not-working-how-can-i-debug

**Comment by emilgoldsmith** [comment] 2021-01-20 21:35
I experience the same problem with the new VSCode plugin. Trice adding the `trace.server: "verbose"` flag to help you all debug, but I can't see any logs anywhere, do you know where I find them?

**Comment by emilgoldsmith** [comment] 2021-01-20 21:35
For anyone else experiencing this I just downgraded which you can do on the "down arrow" beside uninstall, and that works for now :)

**Comment by jmbockhorst** [comment] 2021-01-20 21:37
In VSCode you can go to the "Output" window (Next to the terminal) and select "Elm" from the dropdown. That is where the log is.

**Comment by emilgoldsmith** [comment] 2021-01-21 07:28
Ohh there’s a drop down, thank you! I’ll try to get some logs from there and share it here then, or should I maybe start another issue? I’m thinking they’re probably connected

**Comment by emilgoldsmith** [comment] 2021-01-21 08:50
Here's my logs: https://pastebin.com/fMghMCCK

It looks like it can't discover my elm path anymore maybe? I'm deducing that from the ENOENT on elm/browser's elm.json, and that path is not where I have my elm binary, it's in the yarn global bin which I've added to my path. The previous version discovered this correctly

**Comment by Razzeee** [comment] 2021-01-21 09:49
I don't think its the binary. Can you check if `/home/node/.elm/0.19.1/packages/elm/browser/1.0.2/elm.json` exists? Or where it actually is?

**Comment by emilgoldsmith** [comment] 2021-01-21 11:59
Okay so to be honest I'm quite confused. I was debugging quite a bit and I found out that doing `rm -rf elm-stuff` and then running `elm make src/Main.elm` installed all the packages at the expected place.

I'm developing in a docker container as explained here: https://code.visualstudio.com/docs/remote/containers so my environment is always built from scratch, what it seems like is happening to me is that when I install elm-analyse it creates an elm analyse folder in elm-stuff that then does something funny for the loading of packages from elm make? 

Really not sure, and also confused because it worked with the old version of the extension, right.

Now I added a `postCreateCommand: "rm -rf elm-stuff && elm make src/Main.elm"` to my `.devcontainer.json` and it works, but feels very much like a work around, but hey if it works it works I guess? Definitely don't understand the underlying cause though. I was doing `find / -name "elm.json"` commands before and the packages didn't seem to be anywhere on the file system

**Comment by jmbockhorst** [comment] 2021-01-21 13:01
See https://github.com/elm-tooling/elm-language-server/issues/457 for another Docker conversation.

**Comment by DawidJanczak** [comment] 2021-01-21 13:14
My issue was indeed tied to docker: removing `elm-stuff` inside the container worked. Thanks for the pointer @jmbockhorst!

**Comment by jmbockhorst** [comment] 2021-01-21 13:17
Okay, then I'm closing this as a duplicate of #457. We will be looking at how we can improve the docker experience.

**Closed by jmbockhorst** 2021-01-21 13:17 UTC
Labels: bug

**Comment by Razzeee** [comment] 2021-01-21 15:35
Can you perhaps share your .devcontainer.json?

**Comment by emilgoldsmith** [comment] 2021-01-21 16:45
Sure.

Now it is

```json
{
  "name": "Elm Dev Container",
  "dockerFile": "Dockerfile",
  "settings": {
    "terminal.integrated.shell.linux": "/bin/bash"
  },
  "extensions": [
    "Elmtooling.elm-ls-vscode"
  ],
  "forwardPorts": [
    4000
  ],
  "postCreateCommand": "rm -rf elm-stuff && elm make src/Main.elm"
}
```

And my Dockerfile is

```docker
FROM node:15.5.1-buster

USER node

WORKDIR /home/node

RUN yarn global add \
    elm@0.19.1 \
    elm-test@0.19.1 \
    elm-format@0.8.4 \
    elm-live@4.0.2 \
    uglify-js@3.12.4 \
    elm-verify-examples@5.0.0


ENV PATH "$PATH:/home/node/.yarn/bin"

RUN echo 'PATH="$PATH:/home/node/.yarn/bin"' >> .bashrc
```

**Comment by emilgoldsmith** [comment] 2021-01-21 17:33
So I was messing around with it a bit more, and I think I have quite a bit more understanding now.

So when the problem occurs is when the elm-stuff folder exists, the minimum that ever exists when I've run the server is:

`elm-stuff/0.19.1/`
Populated with:
`d.dat, i.dat, o.dat`

From looking at them those seem to be the already built dependencies. 

Since I'm running in a docker container with a volume to my workspace, that means that when I rebuild my container from scratch which happens relatively regularly at the moment, the cache in `~/.elm` is deleted, and it seems it's not rebuilt because my guess is that it finds the files already built in `d.dat, i.dat, o.dat`.

The language server seems to actively look in the cache though, and therefore misses things there that aren't fetched because it doesn't need to get anything from online when the built files already exist in elm-stuff.

So I see a couple of solutions here:
- I keep my postCreateCommand that deletes those three files, or just the whole elm-stuff folder
- I create a docker volume that will save the cache in between builds inside my git repo included in .gitignore, this way it should still work as a fully shareable dev environment as long as I keep it in the same folder, and can be independent of environments run which is my purpose of using .devcontainer.json
- The language server does some magic I can't imagine what may be.

Let me know if I can be of any help, I'll keep one of my two top solutions for now

**Comment by jmbockhorst** [comment] 2021-01-21 17:43
So here's what is happening: When the language server starts, we run `elm make` which downloads all dependencies and puts them in the cache, then we check the cache for those files.

However, here is what the compiler actually does: First checks `elm-stuff` and checks `d.dat` which has the last "dependency resolution" time for the `elm.json`. If the modification time of `elm.json` equals the cached time in `d.dat`, then it doesn't need to solve any dependencies since the cache files have everything up to date and it uses that to compile. Deleting `elm-stuff` causes `elm make` to download dependencies in the container. The language server doesn't know how to read the `elm-stuff` cache, and if we can't read the dependency source files, we can't do anything.

I'm not sure if there is a good solution, other than trying to read the `elm-stuff` cache for all dependency functions and types, but that is a decent amount of work, although possible.

**Comment by emilgoldsmith** [comment] 2021-01-21 18:08
Thanks for the explanation!

So yeah I guess the cache has the elm code, while the `.dat` files have the javascript code it compiles to, so the compiler doesn't need the elm code when it has already compiled the object files for the dependencies, so it doesn't check the cache of elm code / redownload it when it doesn't find it there.

I think it could be argued to make sense to have a volume for the elm cache, I just think the problem in developer experience terms is it's not very obvious at all that it's necessary right. But yes don't see a great solution other than maybe if elm files can't be found in the cache, the language server deletes the `d.dat` file to invalidate the cache and then runs elm make again before trying another time and THEN crashing?

But deleting files in elm-stuff as an editor tool seems a bit scary for sure, and also maybe a violation of trust?

**Comment by Razzeee** [comment] 2021-01-21 20:27
We could prompt the user if we can delete the folder?

**Comment by emilgoldsmith** [comment] 2021-01-21 21:23
That sounds like a good idea!

By the way my new .devcontainer.json is this that also fixes it, but in a cleaner way in my opinion:

```jsonc
{
  "name": "Elm Dev Container",
  "dockerFile": "Dockerfile",
  "settings": {
    "terminal.integrated.shell.linux": "/bin/bash"
  },
  "extensions": [
    "Elmtooling.elm-ls-vscode"
  ],
  "forwardPorts": [
    4000
  ],
  // We need to have the elm dependency cache mounted as the Elm Language Server depends on it.
  // Without this mount there will be a file (elm-stuff/0.19.1/d.dat) telling the compiler
  // dependencies are cached, but the cache isn't there if we rebuilt the container which will
  // then have deleted the cache at ~/.elm if we don't have it mounted, saving it in our repo
  // in a gitignored directory as we're doing here
  "mounts": [
    "source=${localWorkspaceFolder}/.elm-cache,target=/home/node/.elm,type=bind,consistency=delegated"
  ],
}
```

**Comment by Razzeee** [comment] 2021-01-21 21:52
Please consider moving that upstream https://github.com/microsoft/vscode-dev-containers/blob/master/containers/elm/.devcontainer/devcontainer.json

**Comment by Razzeee** [comment] 2021-01-22 09:32
Then again, not sure if https://github.com/elm-tooling/elm-language-server/issues/457#issuecomment-763289932 would be the better way to do this?

**Comment by emilgoldsmith** [comment] 2021-01-22 09:37
Yeah that's probably a preference thing... 

I think there's an issue with both of them which is that it will error if the directory doesn't exist, so neither of the options will just work out of the box I don't believe. Maybe for the out of the box solution the better way is to create a non-bind volume? Then it should work as long as one doesn't kill your volumes which I don't think is a very usual action

**Comment by Razzeee** [comment] 2021-01-22 09:40
I don't know, not doing that very often :)

**Comment by emilgoldsmith** [comment] 2021-01-22 09:42
Maybe I'll actually change my own setup to do it that way... https://docs.docker.com/storage/volumes/

**Comment by emilgoldsmith** [comment] 2021-01-22 12:43
PR created! Linked above ^^^
