### ISSUE TITLE
Erratic/broken behavior with Neovim's integrated LSP client (2)

### ISSUE THREAD

**Issue by Massolari** [elm-tooling/elm-language-server#598] opened 2021-05-12 14:42 UTC
It's the same issue as #503 

I had this issue before and solved with the suggested solution

```lua
    if client.config.flags then
        client.config.flags.allow_incremental_sync = true
    end
```

but now it's happening again:
![image](https://user-images.githubusercontent.com/12272702/117994578-07b73900-b317-11eb-96be-a14419a8561f.png)

Neovim version:
```
NVIM v0.5.0-dev+1318-g61aefaf29
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compilado por runner@fv-az139-369

Features: +acl +iconv +tui
```

**Comment by Razzeee** [comment] 2021-05-12 15:18
As the server didn't update, did you update nvim or lsp deps for it?

**Comment by Massolari** [comment] 2021-05-12 15:25
Everyday I update my Neovim, all my plugins and my language-servers

**Comment by Razzeee** [comment] 2021-05-12 16:16
So can you go back to yesterday's version, if that worked?

**Comment by Massolari** [comment] 2021-05-12 16:34
It wasn't working.
Actually, I don't remember when this issue has began again.
There is any log that I can look or any info I can give you to help?

**Comment by Razzeee** [comment] 2021-05-12 17:20
I still suspect the client so trying some older clients might be good. Logging should be there but also depends on your client, so refer to nvims docs for that.
You might want to additionally use the log setting in the server for a alot more verbose log

**Comment by mjlbach** [comment] 2021-05-12 20:51
Allow incremental sync is on by default now, so this looks like a bug with the incremental sync implementation on our side, or something server side (we have thousands of people using this with other servers, so I'm surprised by this only affecting elm). Can you reliably reproduce the issue @Massolari

**Comment by mjlbach** [comment] 2021-05-12 20:54
Also fwiw we haven't made any substantial changes to the client for months.

**Comment by Massolari** [comment] 2021-05-12 21:05
@mjlbach 
I just reproduced with minimal settings:
![image](https://user-images.githubusercontent.com/12272702/118043966-719e0580-b34c-11eb-8513-2955939e3274.png)

This project, actually, has no errors.

**Comment by mjlbach** [comment] 2021-05-12 21:07
can you make a repo, include the minimal config and the above file (and any associated elm config files), and in the readme list the rev of nvim-lspconfig, elm-language-server, and neovim.

**Comment by Massolari** [comment] 2021-05-12 21:17
Sure!
I'm doing it right now

**Comment by Massolari** [comment] 2021-05-12 21:27
@mjlbach There it is: https://github.com/Massolari/neovim-elm-issue

**Comment by Massolari** [comment] 2021-05-12 21:29
After open Neovim with `nvim -u init.vim`, just open the file `src/Main.elm` and the error should appear:
![image](https://user-images.githubusercontent.com/12272702/118046597-ecb4eb00-b34f-11eb-836f-35ff4b5a5c0b.png)

**Comment by Massolari** [comment] 2021-05-13 11:25
Update: Using emacs with lsp-mode gives me the same error:

![image](https://user-images.githubusercontent.com/12272702/118119426-bb2a3700-b3c4-11eb-9082-57004297c654.png)

**Comment by Massolari** [comment] 2021-05-13 12:05
Using VSCodium with the Elm extension works fine

**Comment by mjlbach** [comment] 2021-05-13 14:56
If it's also affecting lsp-mode, I doubt it's a client problem...

**Comment by Massolari** [comment] 2021-05-14 14:36
@Razzeee 
Update: Another Neovim LSP client called CoC is showing the same error:
![image](https://user-images.githubusercontent.com/12272702/118286244-a4f5a700-b4a8-11eb-97a4-7bd5a5351214.png)

**Comment by Massolari** [comment] 2021-05-14 15:20
@Razzeee
Reverting elm-language-server to 2.0.3 fixes the problem.
Something on the 2.1.0 is broken

**Comment by Razzeee** [comment] 2021-05-14 16:38
Your not running this with node 10 are you?

**Comment by Massolari** [comment] 2021-05-14 16:42
```bash
node --version            
v14.17.0
```

**Comment by Massolari** [comment] 2021-05-14 16:44
@Razzeee Can you reproduce the error with the repository I created?

**Comment by Razzeee** [comment] 2021-05-14 18:01
No, I'm getting this on startup already and it doesn't seem to do anything when opening the file:

```
Error detected while processing /home/razze/development/neovim-elm-issue/init.vim:
line    7:
E5105: Error while calling lua chunk: ...share/nvim/plugged/nvim-lspconfig/lua/lspconfig/util.lua:11: attempt to index local 'lsp' (a nil value)
Error detected while processing /home/razze/.local/share/nvim/plugged/nvim-lspconfig/plugin/lspconfig.vim:
line   18:
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:11: loop or previous error loading module 'lspconfig'
Press ENTER or type command to continue
```

**Comment by mjlbach** [comment] 2021-05-14 18:02
You need to be on neovim master, seems like you might be on 0.4.x

**Comment by Massolari** [comment] 2021-05-14 18:05
@mjlbach is correct. IMO the easiest way is to use the appimage

**Comment by Razzeee** [comment] 2021-05-14 18:47
I can reproduce it with that. The normal log seems like `Main.elm` is "changed" as soon as it's loaded, without me ever doing anything, so that's weird, but probably not the reason. Will have to see a verboser log to see what updates get send for incremental sync.

**Comment by Razzeee** [comment] 2021-05-14 19:09
Any alternative to 
```
:lua vim.cmd('e'..vim.lsp.get_log_path())
```
Where is the actual path?
https://github.com/neovim/nvim-lspconfig#debugging

**Comment by Massolari** [comment] 2021-05-14 19:16
`:LspInfo` shows the log's path.
You need to add `vim.lsp.set_log_level("debug")` to `init.vim`

**Comment by Razzeee** [comment] 2021-05-14 19:35
Current config is, as that's what's needed for verbose logging:
```
call plug#begin(stdpath('data') . '/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua << EOF
require'lspconfig'.elmls.setup {
 init_options = {
      trace = {
	server = "verbose"}
    }
}
vim.lsp.set_log_level("debug")
EOF
```

**Comment by Augustin82** [comment] 2021-05-15 09:25
I cannot reproduce the bug when opening Main.elm from https://github.com/Massolari/neovim-elm-issue on my setup: running neovim 0.4.3 on Ubuntu 20.04 with node v12.20.2 and elm-language-server 2.1.0.
The only warning I get is about the record in type alias Model having just the one field.

For the record, I do experience the ElmLS reporting false unused types, in my work projects, although it mainly affects an app that takes a long time to compile, so I suspect it's related somehow.

**Comment by Razzeee** [comment] 2021-05-15 09:59
Might still be https://github.com/elm-tooling/elm-language-server/issues/563 as we haven't released a version since?

**Comment by hjwp** [comment] 2021-05-15 22:14
apologise if this sort of "me too" comment isn't helpful, but I was also seeing some spurious errors that look like these and #503 . am using plain vim with coc. 

* specifically, parsing errors show up when making (valid) unsaved edits
* spurious errors disappear when file is saved and new diagnostic is triggered
* spurious errors would also appear on first load.
* reverting to 2.0.3 does seem to fix the problem

not sure if related, but i couldn't get any kind of setting to "only do linting/diagnostics on save" to work?   I tried `elmLS.initializationOptions.elmAnalyseTrigger` set to "save" and "never", neither had any effect.    I also tried `elmLS.onlyUpdateDiagnosticsOnSave` set to `true` but didn't seem to have any effect, i still get linting on unsaved changes.

**Comment by Razzeee** [comment] 2021-05-16 01:03
the `elmAnalyseTrigger` setting doesn't exist anymore, see https://github.com/elm-tooling/elm-language-server/tree/2.1.0#server-settings for the current settings.

The other setting should work https://github.com/elm-tooling/elm-language-server/pull/500
Not really a vim user, but when we tested stuff back then it seemed, like the buffer get's saved continuously without the user actually saving.

**Comment by Razzeee** [comment] 2021-05-16 23:44
Seems like something is off with the npm version, if I just grab https://github.com/elm-tooling/elm-language-server/tree/2.1.0, build it and link it via `npm link` it seems to work fine.

**Comment by pyrho** [comment] 2021-05-17 12:39
I can confirm that with my neovim (v0.5.0-dev+1318-g61aefaf29) lsp setup, checking out 2.1.0 and following the manual install [instructions](https://github.com/elm-tooling/elm-language-server/tree/2.1.0#alternative-compile-and-install-from-source) fixed the weird behaviors.

**Comment by Razzeee** [comment] 2021-05-17 13:35
So it's either an unpinned dependency or something wrong with how we build the npm release.

**Comment by Augustin82** [comment] 2021-05-17 21:45
It seems that with the built/linked version, previous false positives have disappeared (but it's hard to confirm the absence of erratic behavior, of course!).

**Comment by Massolari** [comment] 2021-05-18 18:54
With the built version, it's working fine

**Comment by stoltene2** [comment] 2021-06-26 12:47
Emacs user here. I can confirm that building and installing fixes the parser error.

**Comment by Razzeee** [comment] 2021-06-27 12:10
Did anyone try, if this is still needed with the latest release?

**Comment by stoltene2** [comment] 2021-06-27 17:19
I just grabbed a copy of v2.2.0. After a few minutes, I don't see this happening. I can assume it's fixed since I was on v2.1.0.

**Comment by Razzeee** [comment] 2021-06-27 18:17
Thank you, closing for now then.

**Closed by Razzeee** 2021-06-27 18:17 UTC

**Comment by FraserLee** [comment] 2023-01-22 19:18
Seems like this might be unresolved again. What was changed between 2.1.0 and 2.2.0 that closed this?
