### ISSUE TITLE
Multiple source directories are not getting picked up correctly

### ISSUE THREAD

**Issue by mewhit** [elm-tooling/elm-language-server#117] opened 2019-07-18 23:25 UTC
Hello team.

I can't use go to definition and rename.

That all information I got. 

Tell me if you need more. 

On windows 10.
![image](https://user-images.githubusercontent.com/16157803/61498509-89471580-a991-11e9-8d5e-ad6c704e0043.png)
![image](https://user-images.githubusercontent.com/16157803/61498314-cced4f80-a990-11e9-8d33-932c699d86d9.png)

```
[Trace - 7:17:31 p.m.] Sending request 'textDocument/hover - (36)'.
Params: {
    "textDocument": {
        "uri": "file:///e%3A/dev/someting/src/app/Main.elm"
    },
    "position": {
        "line": 669,
        "character": 23
    }
}


[Trace - 7:17:31 p.m.] Received response 'textDocument/hover - (36)' in 9ms.
No result returned.


[Trace - 7:17:32 p.m.] Sending request 'textDocument/codeAction - (37)'.
Params: {
    "textDocument": {
        "uri": "file:///e%3A/dev/something/src/app/Main.elm"
    },
    "range": {
        "start": {
            "line": 668,
            "character": 23
        },
        "end": {
            "line": 668,
            "character": 23
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 7:17:32 p.m.] Received response 'textDocument/codeAction - (37)' in 1ms.
Result: []


[Trace - 7:17:33 p.m.] Sending request 'textDocument/definition - (38)'.
Params: {
    "textDocument": {
        "uri": "file:///e%3A/dev/something/src/app/Main.elm"
    },
    "position": {
        "line": 668,
        "character": 23
    }
}


[Trace - 7:17:33 p.m.] Received response 'textDocument/definition - (38)' in 0ms.
No result returned.

```

**Comment by Razzeee** [comment] 2019-07-31 22:00
I'm not able to reproduce this on my end :(

**Comment by Razzeee** [comment] 2019-08-16 10:54
Closing due to missing feedback.

**Closed by Razzeee** 2019-08-16 10:54 UTC
Labels: bug
