### ISSUE TITLE
Error on elm-language-server attach due to node higher than 16

### ISSUE THREAD

**Issue by bwells** [elm-tooling/elm-language-server#692] opened 2022-05-18 15:02 UTC
Previously I had a working config for neovim and elm-language-server. I'm not sure if the problem is in elm-language-server, node, or the neovim side. 

## Expected Behavior
Previous integration worked fine.

## Current Behavior
    [START][2022-05-18 08:47:05] LSP logging initiated
    [ERROR][2022-05-18 08:47:10] .../vim/lsp/rpc.lua:420	"rpc"	"elm-language-server"	"stderr"	"(node:79362) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time\n(Use `node --trace-warnings ...` to show where the warning was created)\n"
    [ERROR][2022-05-18 08:47:10] ...lsp/handlers.lua:454	"Unhandled Rejection at: Promise [object Promise] reason:, TypeError: Failed to parse URL from /Users/kremlan/.local/share/nvim/lsp_servers/elmls/node_modules/@elm-tooling/elm-language-server/node_modules/web-tree-sitter/tree-sitter.wasm"

I can confirm that the referenced `tree-sitter.wasm` location exists at that location. 

## Possible Solution
It seems unlikely that elm-language-server itself changed causing the break based on the date of the last release, but I have no idea when I had previously updated my installation. I can't tell from the provided error message if this is a problem from within elmls, an incompatibility with a node upgrade, or an error occurring within neovim. 

## Steps to Reproduce (for bugs)
1. Open any elm fine in neovim 
2. Introduce a syntax error
3. Note that no LSP diagnostics are provided 

## Context
elm-language-server integration is now completely non-functional. 

## Your Environment
Neovim using lsp-config and lsp-installer. 
dotfiles available at https://github.com/bwells/dotfiles/tree/master/nvim

* Version used: elm-language-server 2.2.1
* Editor used: neovim 0.7
* Environment name and version (e.g. node.js 5.4): Node v18.1.0
* Operating System and version: macOS 12.4

**Comment by razzeee** [comment] 2022-05-18 18:15
Did neovim or a plugin that's used for communicating with LSP change?

Did you check if `/Users/kremlan/.local/share/nvim/lsp_servers/elmls/node_modules/@elm-tooling/elm-language-server/node_modules/web-tree-sitter/tree-sitter.wasm` exists?

**Comment by bwells** [comment] 2022-05-18 18:20
Also, thanks!

**Comment by razzeee** [comment] 2022-05-18 18:34
As it's a `.lua` error, it should be a neovim problem.

**Comment by bwells** [comment] 2022-05-18 18:50
FWIW `"Unhandled Rejection at: Promise [object Promise]` looks a lot more like JS/TS than Lua. My best guess is still something on the elmls side.

Can you provide any advise on how to more directly test elmls in a standalone mode?

**Comment by bwells** [comment] 2022-05-19 10:24
I've been able to track this down to a seeming incompatibility between elm-language-server and Node 18.x. Reverting node to 16.x has resolved the issue for me. Even more weirdly, the issue seems to resolve if I have both 18.x and 16.x installed locally with 18.x first in the path, but is reproducible if only 18.x is installed (via brew).

Presumably I'm not the only person using elmls with Node 18.x and this issue involves details more specific to my system. I'm happy to help with further debugging, but otherwise I'll just count the workaround as sufficient for now.

**Comment by BokuBeam** [comment] 2022-06-01 02:11
I was having this issue in Linux with the Helix editor. I used nvm to switch from 18.x to 16.x and that fixed the problem for me as well.

**Comment by JasonMFry** [comment] 2022-06-02 21:40
> I've been able to track this down to a seeming incompatibility between elm-language-server and Node 18.x. Reverting node to 16.x has resolved the issue for me. Even more weirdly, the issue seems to resolve if I have both 18.x and 16.x installed locally with 18.x first in the path, but is reproducible if only 18.x is installed (via brew).

This fixed my problem :D

- macos 12.3.1
- Doom Emacs 28.1
- I had installed `node` via brew, so to downgrade I had to do `brew uninstall --ignore-dependencies node && brew install node@16 && brew link node@16`

**Comment by razzeee** [comment] 2022-06-03 07:08
Might be connected with https://github.com/tree-sitter/tree-sitter/issues/1765

**Comment by Krzysztof-Cieslak** [comment] 2022-06-06 16:29
@razzeee, the log reported in the first post in this thread is the same as what I've observed when investigating my tree sitter issue, so yeah, it seems to be related to it

**Comment by matt-savvy** [comment] 2022-07-17 21:46
I'm having what looks like the same exact issue and switching node from v18.4.0 back to node v16.14.2 seems to have done the trick.

**Comment by brendantang** [comment] 2022-07-21 14:23
Same issue here. I tested using node 16.1.0, 16.16.0, and 18.6.0. Language server provided no feedback on either 16.16.0 or 18.6.0, but works great on 16.1.0. I used both helix editor and vim with ALE, so I wonder if that helps narrow down the problem?

**Comment by jweir** [comment] 2022-08-18 22:28
One thing is maybe put a warning in the READM E that this might not work versions of node greater than 16.x.  I just spent the last several hours trying to get Vim + CoC to work with Elm.  It was working, then I brew upgraded vim, and node, and some other things.  I just observed of my developers having it on v17.5.0

**Comment by heyakyra** [comment] 2022-09-06 02:14
> It needs to be fixed in upstream, nothing we can do in this repo for now.

Is there an upstream report?

**Comment by nomoredarts** [comment] 2022-12-02 08:20
- Can not build from source with node 19
- Package downloaded from npm doesn't start

![starting](https://user-images.githubusercontent.com/6137314/205247988-e80ab2ba-409f-4bc7-b73f-610a10b05726.png)

All works fine when building under node v16.

**Comment by VlkrS** [comment] 2022-12-10 13:04
I found a workaround in tree-sitter/tree-sitter:

Adding 

try {
	//@ts-ignore
	delete WebAssembly.instantiateStreaming
} catch {}

to the top of elm-language-server's index.js makes it work again.

**Comment by razzeee** [comment] 2022-12-10 16:01
As far as I understood, it has been fixed in upstream, so we just need a release to happen on their side.

**Comment by andys8** [comment] 2023-01-16 12:55
Reference to potential fix, release pending:

https://github.com/tree-sitter/tree-sitter/pull/1913

**Comment by nihil2501** [comment] 2023-01-28 07:30
> I found a workaround in tree-sitter/tree-sitter:
> 
> Adding
> 
> ```
> 	
> //@ts-ignore
> 	delete WebAssembly.instantiateStreaming
> } catch {}
> ```
> 
> to the top of elm-language-server's index.js makes it work again.

Worked for me as well. [Link to original suggestion](https://github.com/tree-sitter/tree-sitter/issues/1765#issuecomment-1271790298)

**Comment by kumkee** [comment] 2023-04-25 18:16
> > I found a workaround in tree-sitter/tree-sitter:
> > Adding
> > ```
> > 	
> > //@ts-ignore
> > 	delete WebAssembly.instantiateStreaming
> > } catch {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the top of elm-language-server's index.js makes it work again.
> 
> Worked for me as well (after correcting for typo of missing `try`). [Link to original suggestion](https://github.com/tree-sitter/tree-sitter/issues/1765#issuecomment-1271790298)

If I am using neovim + lazy, where should I add this few lines?

**Comment by VlkrS** [comment] 2023-04-25 18:28
@kumkee at the top of index.js in elm-languageserver

**Comment by hovsater** [comment] 2023-04-27 20:57
Seems like a release was made three weeks ago now. https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.8

**Comment by razzeee** [comment] 2023-04-27 21:33
See https://github.com/elm-tooling/elm-language-server/pull/954

**Comment by jmbockhorst** [comment] 2023-05-05 14:07
Can this be closed after the latest release?

**Comment by kumkee** [comment] 2023-05-14 03:28
> See #954

I can confirm the update work with node 20.1.0

**Closed** 2023-05-14 05:27 UTC
