### ISSUE TITLE
Irrelevant type inference warning while correct typing is already present

### ISSUE THREAD

**Issue by Augustin82** [elm-tooling/elm-language-server#347] opened 2020-10-23 12:16 UTC
## Expected Behavior
Type inference hints should only 1) be correct and 2) only happen when there is no typing or the typing is wrong

## Current Behavior
Erroneous typings are suggested in place of existing typings.
![Selection_278](https://user-images.githubusercontent.com/2370810/97002464-539cbf00-153a-11eb-9150-df79ef03399e.jpg)

## Possible Solution
No idea, sorry

## Steps to Reproduce (for bugs)
No idea, sorry

## Context
Nothing special.

## Your Environment
* Version used: 1.13.1
* Editor used: NeoVim v0.4.3 with CoC.nvim 0.0.79-a900a8535c
* Environment name and version (e.g. node.js 5.4): node v10.22.1
* Operating System and version: Ubuntu 18.04.5

**Comment by Razzeee** [comment] 2020-10-24 11:02
Can you try if you still get this after restarting the server? Is it consistent in that way?

**Comment by Augustin82** [comment] 2020-10-24 11:09
Unfortunately, I am not sure how to reproduce in the first place, although I've had it happen several times.

**Comment by jmbockhorst** [comment] 2020-10-30 21:45
Sometimes this can happen when making changes because of how the file is parsed with incorrect syntax.

**Comment by Razzeee** [comment] 2020-11-07 15:16
I'm going to close this, until we can reproduce it.

**Closed by Razzeee** 2020-11-07 15:16 UTC
