### ISSUE TITLE
Incomplete suggestions when importing multiple modules under same alias

### ISSUE THREAD

**Issue by Yarith** [elm-tooling/elm-language-server#526] opened 2021-02-20 15:13 UTC
I like to combine multiple modules into one alias, so i do only have one keyword to remember when operating on various types. Something where the current suggestions popup behavior comes in my way. Currently my main reason when coming out of the flow, besides problems when i need to restart language server or reload vscode.

So i do stuff like this:
```elm
import Element as E exposing (Element, Attribute)
import Extensions.Element as E
import Tuple.Extra as Tuple
-- and more like for http, html, parser, task and so on.
-- There are a lot of extra packages, also there are some defined in local source code.

none : Element msg
none = 
    -- https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element#none
    -- If you type the dot, it only shows the suggestions for module Element, but not for Extensions.Element
    E.none

noneAttribute : Attribute msg
noneAttribute = 
    -- Defined in local source file
    -- If you type the dot, it only shows the suggestions for module Element, but not for Extensions.Element
    E.noneAttribute

fullnameText : ( String, String ) -> String
fullnameText = 
    -- https://package.elm-lang.org/packages/pd-andy/tuple-extra/latest/Tuple-Extra#join
    -- If you type the dot, it only shows the suggestions for Tuple.Extra, but Tuple is implicitly imported.
    -- As soon as you import the Tuple module explicitly, it will omit the suggestions for Tuple.Extra. 
    -- If you put the module Tuple under Tuple.Extra it will again show the suggestions for Tuple.
    -- It seems to be only the first one in the list. After executing elm-format Tuple is always first.
    Tuple.join " "
```

## Expected Behavior
If you type the dot character after the overloaded alias, it should show suggestions from all modules for this module alias.
Bonus: Hovering over the overloaded alias should show documentation of all modules, but is not important for me.
Bonus: Hovering over the aliased qualified identifier should show the true source module. If there is a conflict, then the elm compiler gives already a good error message.

## Current Behavior
If you type the dot character after the overloaded alias, it shows only the suggestions from the first imported module in the current document. Implicit imports have always lower priority than aliased imports.

## Possible Solution
I have not looked into the code, but from experience i think the search is breaking after the first module, if there is none it looks for implicit imports. Handling only one instance makes it easier to ensure the behavior. There can not be zero modules, which would be representable in a simple list. Maybe allowing a list of modules in the lookup will not complicate this stuff too much. I can imagine that this can be a simple change.

## Steps to Reproduce (for bugs)
1. Setups an elm language server environment
2. Copy the example code from above into an module
3. Override the dots like written in the comments to open the suggestions popup.
4. It only shows the members of the first imported module.

Also following will be noticable, but is more a problem with `elm-format`:
In case of `Tuple`, it shows `Tuple.Extra` as import suggestions. If you select it and import the module, then elm-format will remove it afterwards because of the alias on the same module. Newcomers could be confused, if after the import the error is gone and after save it appears again. The user can not see that the module was removed again. Also it prevents to disambiguate with qualified identifier if there is a name conflict only on the overloaded alias. This is maybe something for an other issue.

## Context
With combining modules to the same alias i can simulate a feature which may be called "module extensions". Stuff that could be in the main module, but they are so rarely used or are not fundamental, so they are moved to extra packages. I have written above two examples how i am using it. 

## Your Environment

* Version used: 2.0.3
* Editor used: 
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Datum: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
Betriebssystem: Windows_NT x64 10.0.19042
```
* Environment name and version (e.g. node.js 5.4): v15.6.0
* Operating System and version: Windows 20H2 (Build 19042.804)

**Comment by jmbockhorst** [comment] 2021-02-21 17:28
Duplicate of #405.

**Closed by jmbockhorst** 2021-02-21 17:28 UTC
