### ISSUE TITLE
Support sub-projects / elm-review

### ISSUE THREAD

**Issue by lydell** [elm-tooling/elm-language-server#187] opened 2019-10-26 15:08 UTC
## Expected Behavior
When opening a file in a sub-project, imports can be resolved.

Use case: [elm-review](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/). elm-review puts a sub-project in the `review/` folder, next to your regular `src/`.

## Current Behavior
When opening a file in a sub-project, imports can not be resolved.

> MODULE NOT FOUND - You are trying to import a `Review.Rule` module:
>
> ...

## Steps to Reproduce (for bugs)

```
# Install Elm and elm-review:
❯ echo '{"private":true}' > package.json
❯ npm i elm elm-review

# Make an Elm project:
❯ npx elm init
# Answer "Y".

# Set up elm-review:
❯ npx elm-review init
# Answer "Y".

# Make a simple Elm src file:
❯ echo 'module Main exposing (..)
  x = 1' > src/Main.elm

# Install packages for elm-review:
❯ cd review
❯ npx elm make ReviewConfig.elm
Starting downloads...
Dependencies ready!
Success! Compiled 1 module.

# Open VSCode for the whole repo:
❯ cd ..
❯ code .

# In VSCode:
#
# 1. Open src/Main.elm. Notice how "everything works".
# 2. Open review/ReviewConfig.elm. Notice how the `Review.Rule` import cannot be found.

# Open VSCode inside review/ instead:
❯ cd review
❯ code .

# In VSCode:
#
# 1. Open ReviewConfig.elm. Now the `Review.Rule` import can be found!
```

## Context
elm-review is really cool. It would be very nice to be able to just do `code .` in the repo root and be able to work on source code, tests and review rules all at the same time.

## Your Environment
* Version used: 0.7.1
* Editor name and version:  VSCode 1.39.2
* Environment name and version: Node.js v12.8.0
* Operating System and version: macOS Mojave

**Comment by Razzeee** [comment] 2019-10-27 02:12
The problem here is, that we end up calling elm from the top level folder.

`elm make review/ReviewConfig.elm --report json --output /dev/null` which then tries to make sense of the top level elm.json with the target file.

The other approach, always compiling with the nearest elm.json would work in these case. But will likely break cases where you "inline" packages through `source-directories`.

It kind of fits together with https://github.com/elm-tooling/elm-language-server/issues/118 so a way to setup an array of tuples that contains an entry point and the correct elm.json would be the cleanest solution. But not sure that it's we should solve this in the scope of this project.

**Comment by lydell** [comment] 2019-10-27 08:37
> But will likely break cases where you "inline" packages through `source-directories`.

Do you have an example of this?

**Comment by Razzeee** [comment] 2019-10-27 15:38
For example in this repo.
https://github.com/cgtuebingen/infomark-ui/blob/master/elm.json#L5

The top application is using elm-mdm, but from the `source-directories` instead of depending on a package from the package index. So in that case you want the top level elm.json to be used for the elm-mdm compilation I guess?

**Comment by lydell** [comment] 2019-10-27 16:26
I see, thanks. Maybe there’s a clever way of supporting both…

**Comment by Razzeee** [comment] 2019-10-27 20:16
Having an optional file like `.elmsettings` with an array of tuples like:

So for your example this would work I guess.

```
{
"projects": [
	{"config": "elm.json", "entry":"src/Main.elm"},
	{"config": "review/elm.json", "entry":"review/ReviewConfig.elm"}
]
}
```

When there is a folder that's not mentioned in there I would probably default to the current behavior.

**Comment by klazuka** [comment] 2019-10-28 15:03
This scenario works in intellij-elm because we ask the user to "attach" `elm.json` files. This is done via UI, but in your case, using a dotfile would achieve the same thing.

@Razzeee Why do you need the `entry` key?

The only thing I persist for each Elm "project" is the path to the `elm.json` file. Then when I boot up, I read the persisted list of projects and I create an index that maps every file in the "workspace" to the `elm.json` file whose source-directory contains it and the module name is valid (e.g. if source-directory is `src` and a file is `src/Foo/Bar.elm`, then the module name of `Bar.elm` must be `Foo.Bar`).

If a file exists in a location where more than one Elm project's `source-directory` matches it, then I associate it with the `elm.json` file whose path distance is shortest. This may result in unexpected behavior, but so far I haven't seen any problems with it. This scenario is common for package projects which include an example app.

**Comment by Razzeee** [comment] 2019-10-29 00:03
Well, having the entry set by the user just tries to dodge the need to have an algorithm to figure out where the entry of an application is, as there might be multiple places that look like a valid entry, but the user expects some not to be used? It might also just be a very wild usecase.

**Comment by klazuka** [comment] 2019-10-29 14:59
Configuring the entry-point seems brittle. What happens if the user renames the file? Or moves the `main` function to a different file?

intellij-elm infers the entry-point by searching for a function named `main` whose type is `Platform.Program`. This has caused some confusion in the past, so it's not perfect, either, but I think it's preferrable over making it explicit.

**Comment by Razzeee** [comment] 2019-10-29 15:47
You are probably right, I was just thinking of how `package.json` has the ability to have a `bin` setup https://github.com/elm-tooling/elm-language-server/blob/master/package.json#L60

So I was influenced by that. I agree, that it's also not perfect. And then both of the approaches only work for applications anyway. But we're side tracking this ticket.

**Comment by lydell** [comment] 2019-10-29 19:10
Maybe we could show a dialog if we find more than one elm.json when walking up the file tree from a just-opened Elm file, asking the user which one to use and saving the result to `./.vscode/settings.json`.

**Comment by Razzeee** [comment] 2019-10-30 08:38
That would work for vscode, but we really want something that can also work in other editors

**Comment by lydell** [comment] 2019-11-01 19:06
After upgrading to Elm 0.19.1, I get this error on the `module` keyword in `review/tests/*.elm` in VSCode:

```
CONFUSING FILE - I am getting confused when I try to compile this file:

    /Users/lydell/stuff/elm-test-issue/review/tests/DemoRuleTest.elm

I always check if files appear in any of the "source-directories" listed in your
elm.json to see if there might be some cached information about them. That can
help me compile faster! But in this case, it looks like this file may be in
either of these directories:

    /Users/lydell/stuff/elm-test-issue/review
    /Users/lydell/stuff/elm-test-issue/review/tests

Try to make it so no source directory contains another source directory!
```

See also: https://github.com/elm-explorations/test/issues/114

**Comment by Razzeee** [comment] 2019-11-02 19:17
But only if your in the file?

**Comment by lydell** [comment] 2019-11-02 19:22
Sorry, I’m not sure what you mean?

**Comment by Razzeee** [comment] 2019-11-02 19:37
I think the error shows up, when your in the test file and save?

It does not happen when your not in a test file?

**Comment by lydell** [comment] 2019-11-02 19:44
If I do `cd review/ && code .` and then open a test file the `module` keyword is underlined with red immediately. I don’t need to save. The files directly inside `review` don’t have this problem.

**Comment by sentience** [comment] 2020-01-03 02:58
Our main Elm codebase at Culture Amp is a single repo containing 27 elm.json files, many of which share the same “library” modules using common `source-directories`. Resolving this issue is therefore crucial to us, and I'm going to be putting some time into a proposed solution.

I'm working on a solution to this now.

**Comment by sentience** [comment] 2020-01-06 06:37
☝️ Sharing my WIP just so @Razzeee can see what direction I'm headed in, in case he thinks it's a bad idea.

**Comment by sentience** [comment] 2020-01-07 13:27
My branch is coming along well, although it's going to be a pretty big change to the language server's internals. elm-format is working fine for me across multiple elm.json files on my branch, now, which I think proves the concept. I just need to finish moving all the other language server features over to the same multi-elm.json-supporting architecture, then do a big refactoring pass to clean up some of the repeated code and poorly-factored concerns.

I feel like I'm over the peak and coasting down the other side of the hill on this one, though. 🤞

**Comment by sentience** [comment] 2020-01-09 12:56
#205 is now hypothetically feature-complete!

There is still a significant amount of refactoring to be done to tidy things up before this is merged, and considerable testing will be necessary to ensure anything that I've broken is fixed up. That said, anyone who likes to live on the edge, or who is particularly dependent on support for multiple elm.json files may wish to take this for a test drive.

In other words: bug reports welcome!

**Closed** 2020-01-26 23:04 UTC
