### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by edkelly303** [elm-tooling/elm-language-server#610] opened 2021-06-27 16:35 UTC
## Expected Behavior
Given this code:
```elm
module ElmLSBug exposing (..)


update : FrontendMsg -> FrontendModel -> ( FrontendModel, List Effect )
update msg model =
    case msg of
        RecipeView_StepClicked stepId ->
            case model.page of
                RecipeViewPage state ->
                    ( { model
                        | page =
                            RecipeViewPage
                                { state
                                    | stepStatus =
                                        let
                                            stepStatus1 =
                                                Dict.update stepId
                                                    (Maybe.map
                                                        (\status ->
                                                            case status of
                                                                Locked ->
                                                                    status

                                                                Open ->
                                                                    Active { startedAt = model.now }

                                                                Active { startedAt } ->
                                                                    Completed { startedAt = startedAt, completedAt = model.now }

                                                                Completed _ ->
                                                                    status
                                                        )
                                                    )
                                                    state.stepStatus

                                            completedSteps =
                                                stepStatus1
                                                    |> Dict.filter
                                                        (\_ v ->
                                                            case v of
                                                                Completed _ ->
                                                                    True

                                                                _ ->
                                                                    False
                                                        )
                                                    |> Dict.keys
                                                    |> Set.fromList
                                        in
                                        stepStatus1
                                }
                      }
                    , []
                    )
```
I would expect the language server not to raise any parsing errors, as this seems to be valid Elm code and the Elm compiler will parse it happily.

## Current Behavior
The language server shows several errors in VS Code when I open the file:
![image](https://user-images.githubusercontent.com/12986896/123552195-f2825680-d76c-11eb-8260-5db8b92a83a5.png)

When I hover over these errors, it says "Parsing error."

If I save the file, the errors go away. But if I close and reopen the file, they come back.

## Steps to Reproduce (for bugs)
See code sample above (apologies for the length, I tried to cut it down as much as I had time to do)

## Context
It's not a serious problem, just a minor annoyance that the errors are misreported.

## Your Environment
* Elm Language Server VS Code plugin 2.2.0
* VSCode 1.57.0
* node.js 14.16.0
* Xubuntu 21.04
* elm-format 0.8.4

**Comment by Razzeee** [comment] 2021-06-27 16:39
Probably duplicate of https://github.com/elm-tooling/elm-language-server/issues/608

**Comment by Razzeee** [comment] 2021-06-27 23:29
Yeah, seems to parse fine in tree-sitter-elm itself as in #608

**Comment by roberth** [comment] 2021-09-20 10:12
I am experiencing a similar problem and the errors also reappear when I type anywhere in the file.

**Closed** 2022-02-04 13:52 UTC
Labels: bug
