### ISSUE TITLE
No errors visible in neovim + coc.

### ISSUE THREAD

**Issue by brzezinskip** [elm-tooling/elm-language-server#348] opened 2020-10-26 21:55 UTC
## Expected Behavior
ELS 1.13.1 + COC combination should display errors and warnings in neovim (it does in VSC). It does work fine on 1.11.0.

## Current Behavior
No errors are being displayed. CocInfo, amongst other lines, has this one `[Error  - 10:12:16] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'uri' of undefined` which I believe may be the root of the issue here.

## Possible Solution
Unfortunately, no idea. I've been trying to find out what library could be causing the above error but no luck.

## Steps to Reproduce (for bugs)
1. Install 1.13.1 version of ELS.
2. Open any .elm file
3. Make a mistake so that compiler fails.
4. Notice there's no error shown in the place you broke the code at.

## Context
I've tried upgrading my ELS because of some other small issue I've been having in older versions. I did that by cloning the repo and manually linking. Unfortunately it didn't work, so I unlinked and installed the latest version through npm. No luck there either, so in the end, I just reverted to 1.11.0 as it worked fine there before for me

## Your Environment
* Version used: 1.13.1
* Editor used: Neovim
* Environment name and version (e.g. node.js 5.4): node v12.13.1
* Operating System and version: osx catalina 10.15.7

**Comment by Razzeee** [comment] 2020-10-28 01:47
This is the relevant version diff https://github.com/elm-tooling/elm-language-server/compare/1.11.0...1.12.0

**Comment by andys8** [comment] 2020-10-29 10:59
I did give it a try with my setup. Errors seem to work fine with `elm-language-server` 1.13.1.

```
vim version: VIM - Vi IMproved 8.2 8021704
node version: v12.15.0
coc.nvim version: 0.0.79-d3293597d1
```

Can you reproduce it with a public repository, too?
What's the exact version of CoC you're using?

**Comment by brzezinskip** [comment] 2020-10-29 12:35
Hey Andy, here's an info I've gotten from CocInfo

```
vim version: NVIM v0.4.4
node version: v12.13.1
coc.nvim version: 0.0.79-230b8a7247
```
I'll try reproducing with a public repo asap. Thanks for looking into it!

**Comment by Augustin82** [comment] 2020-10-30 22:34
I've got this on one computer. It works fine on the other, and I cannot figure out a difference in setups (apart from the problematic computer running node 14, but I since switched to node 10 and it didn't fix anything).

```
[Trace - 11:15:22 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/augustin/Code/HearthstoneDeckViewer/src/Main.elm",
        "languageId": "elm",
        "version": 1,
        "text": <removed for concision>
    }
}

[Trace - 11:15:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'uri' of undefined"
}


[Error  - 11:15:22 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'uri' of undefined
```

**Comment by Razzeee** [comment] 2020-10-31 02:04
I found and fixed that, let's wait for a review and I'll push an update this weekend.

**Comment by Augustin82** [comment] 2020-10-31 12:01
FYI, I installed elmLS from that branch and could not seem to reproduce the error (so, it looks like it's fixed in that branch, indeed).

Many thanks, @Razzeee!

**Comment by brzezinskip** [comment] 2020-11-02 09:11
That's awesome, thanks a lot!!

**Comment by Razzeee** [comment] 2020-11-07 15:12
The new version has been released yesterday, so I'm going to close this.

**Closed by Razzeee** 2020-11-07 15:12 UTC
