### ISSUE TITLE
[CoC/neovim] Go to definition fails for some functions

### ISSUE THREAD

**Issue by Augustin82** [elm-tooling/elm-language-server#254] opened 2020-04-16 12:03 UTC
## Expected Behavior
I expect "go to definition" to work regardless of the context.

## Current Behavior
For some functions, whether they are in the same file or not, I instead get an error from CoC:
`[coc.nvim] Definition not found`

Looking into the log with `:CocInfo`, this is what I see:
```
[Info  - 1:54:25 PM] A definition was requested
[Error  - 1:54:25 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: anonymousFunctionExprNodes.flatMap is not a function
  Code: -32603
```

## Possible Solution
I have none, sorry!

## Steps to Reproduce (for bugs)¶
I don't have an SSCCE, sorry, but i've had the bug occur on my latest pet project, which consists of one Main.elm file, so I figure it's OK to use it to showcase the issue? Let me know if it is not.
1. `git clone --single-branch --branch animation-test git@github.com:Augustin82/0h-n0`
2. open `./0h-n0/src/Main.elm`
3. go to the use of `toColor` (l.135) and try to go to definition: it works
4. go to the use of `fromColor` (l.140) and try to go to definition: it does not work

## Context
Going to the definition would be peachy!

## Your Environment
* Version used: 1.7.1
* Editor used: neovim
* Environment name and version (e.g. node.js 5.4): nodejs 10.20.1
* Operating System and version: Ubuntu Gnome 18.04

**Comment by Razzeee** [comment] 2020-04-16 20:01
hrm, that seems to work for me. even when I run 1.7.1 instead of master, can you check again?

**Comment by Augustin82** [comment] 2020-04-16 20:16
I've tested several times, including cloning the repo in a new directory.

What are things I could do to check if it's due to my neovim config, or to my CoC setup, or something else? Should I add debugging to the Elm LS code to get more information on that error (code 32603), or is it a red herring?

**Comment by Razzeee** [comment] 2020-04-16 20:21
I think the best thing would be, if you were able to reproduce it in vscode.

**Comment by Augustin82** [comment] 2020-04-16 20:26
Ok, I'll try to install it and check.

**Comment by Augustin82** [comment] 2020-04-16 20:43
It works fine in VSCode, like you said. Kudos on the feature set there, btw, it looks impressive, I'm almost tempted to try it for a while =P

So, how should I go about finding the problem, which is most likely in the way CoC and ElmLS talk, right?

**Comment by Augustin82** [comment] 2020-04-16 20:52
Oh, ok, so, looking at the source code, I see the error comes from https://github.com/elm-tooling/elm-language-server/blob/a43340d5cbcb3ffbd8003be0c9237deaa3e3f1c3/src/util/treeUtils.ts#L1125, which seems to be related to anonymous expression.

And indeed, if I extract that anonymous function into a regular one, then gotodef work for both the newly extracted function AND the `fromColor` function which was not working before.

I'm gonna check in my real project if gotodef were failing within anonymous, parenthesis-enclosed functions, but I'm pretty sure it is the case. Is this somehow actionable?

**Comment by Razzeee** [comment] 2020-04-16 22:14
I'm fairly confused by this. Does that happen, when you just open the editor and directly go to the definition? Or do you need to change stuff before that to get it to happen?

In theory the server shouldn't be able to fail on that expression. I guess the only way is, when the server somehow fails to build tho ast, but I'm not sure why that would happen in vim. Does catching a possible `null` in `anonymousFunctionExprNodes` do anything? (It shouldn't even be possible to be null)

**Comment by Augustin82** [comment] 2020-04-17 12:06
Indeed, adding the following in TreeUtils.js and restarting CoC resulted in the gotodef working.
```
        if (node && node.type === "parenthesized_expr") {
            const anonymousFunctionExprNodes = this.descendantsOfType(node, "anonymous_function_expr");
            if (!anonymousFunctionExprNodes.flatMap) {
                return;
            }
            const match = anonymousFunctionExprNodes
                .flatMap((a) => a.children)
                .find((child) => child.type === "pattern" && child.text === functionParameterName);
            if (match) {
                return match;
            }
        }
```

I don't mind leaving it there as a hotfix for now, but can I do anything to try and pinpoint the actual problem, and maybe possibly fix it? I'm very new to LSPs but I don't mind hacking at it until it works ;)

**Comment by Razzeee** [comment] 2020-04-17 12:48
The real question is how this happens, best would be to figure that out and create a test for it here https://github.com/tree-sitter/tree-sitter/blob/82fab90c0b91cc57a949b9d96768d7f3b7a621e4/lib/binding_web/test/node-test.js#L315

Then we could show it to the maintainers of tree-sitter and figure out how to advance.

**Comment by Augustin82** [comment] 2020-04-17 13:05
I'm afraid I don't understand how to translate what I have observed (gotodef fails when the function whose definition you're trying to reach is wrapped in a parenthesized lamda function) into such a test =/ Any pointers from one more familiar? Or should I create an issue over there, linking here, and asking for help?

**Comment by Razzeee** [comment] 2020-04-17 13:33
I'm not so sure either, can you check/print `anonymousFunctionExprNodes` if it's `null`? We could at least open a conversation over at their repo around that. I'm not sure how/if that's something we cause somehow.

**Comment by Augustin82** [comment] 2020-04-21 13:57
@Razzeee they said:
>I'm going to close this one out for now because currently, it sounds like you are investigating an issue with elm-language-server or tree-sitter-elm.

What's our next step? What can I do to help?

**Comment by Razzeee** [comment] 2020-04-21 14:12
I think the best would be to get someone else to test it with coc and neovim and confirm, that it breaks, like it does for you.

Then generating a trace that we can feed  into https://microsoft.github.io/language-server-protocol/inspector/ or replay (somehow) and maybe attach a debugger to the server.

Maybe @andys8 can help

**Comment by andys8** [comment] 2020-04-21 15:09
I can reproduce it in Vim.
I can't reproduce it in VSCode.

```
[Trace - 5:08:06 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "A definition was requested"
}


[Info  - 5:08:06 PM] A definition was requested
[Trace - 5:08:06 PM] Received response 'textDocument/definition - (10)' in 3ms. Request failed: Request textDocument/definition failed with message: anonymousFunctionExprNodes.flatMap is not a function (-32603).
[Error  - 5:08:06 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: anonymousFunctionExprNodes.flatMap is not a function
  Code: -32603 
```

```
vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 13:23:00)
node version: v12.5.0
coc.nvim version: 0.0.78-6e3ecc04cf
term: dumb
platform: linux
elm-language-server  --version: 1.7.1
```

**Comment by Razzeee** [comment] 2020-04-21 15:18
Does this mean the node context via vim is different? Searching for that error basically says, it's not supported in your browser https://stackoverflow.com/questions/55530690/javascript-flatmap-method-over-array-flatmap-is-not-a-function

**Comment by andys8** [comment] 2020-04-21 15:19
goto def fromColor not working 
```
color1 state =
    Animator.color state
        (\s ->
            case s of
                Ready ->
                    fromColor blue

                Loading ->
                    fromColor red
        )
```

goto def fromColor working

```
color1 state =
    let
        f =
            \s ->
                case s of
                    Ready ->
                        fromColor blue

                    Loading ->
                        fromColor red
    in
    Animator.color state f
```

**Comment by Razzeee** [comment] 2020-04-21 17:45
Hrm we already define `es6` and `es2019`

**Comment by andys8** [comment] 2020-04-21 17:47
`es5` != `es6`

**Comment by Razzeee** [comment] 2020-04-21 18:12
![Peek 2020-04-21 20-10](https://user-images.githubusercontent.com/5943908/79898934-53492d00-840c-11ea-8b2c-b147fe5f8bdd.gif)

just tried myself in vim on manjaro. Language server installed via npm or npm link works fine for me.

**Comment by andys8** [comment] 2020-04-21 18:26
I can confirm it's working with Vim and `elm-language-server` 1.7.1 installed with npm and it's not working with 1.7.1 installed with nix.

**Comment by Augustin82** [comment] 2020-04-21 18:30
I installed using yarn. I'll try using npm (if I ever sort the problems with paths and authorizations and stuff...).

**Comment by andys8** [comment] 2020-04-21 18:31
Nix seems to use node 10:
https://github.com/andys8/nixpkgs/blob/523fe988217eaa56952c2a87760fef612c857bee/pkgs/development/compilers/elm/packages/generate-node-packages.sh#L9

**Comment by andys8** [comment] 2020-04-21 18:33
`flatMap` requires `node` >= 11.
![image](https://user-images.githubusercontent.com/13085980/79900940-5396f780-840f-11ea-9bfd-41fb66d2ea63.png)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

**Comment by Augustin82** [comment] 2020-04-21 18:58
Would it make sense to add this in the code? https://github.com/jonathantneal/array-flat-polyfill

**Comment by andys8** [comment] 2020-04-21 19:02
There's also this: https://github.com/ryanelian/ts-polyfill

I'm surprised if there is no poly-filling going on, if you target es5 or es6.

**Comment by andys8** [comment] 2020-04-21 19:13
So current theory is: Output will not work with node <= 10 and has to be verified.

Comparison with VS Code is (I guess) not useful because it's integrated as plugin and in a different way.

**Comment by Razzeee** [comment] 2020-04-22 00:19
https://github.com/elm-tooling/elm-language-server/tree/workaround-flatmap might help

**Comment by andys8** [comment] 2020-04-22 15:35
> I installed the branch with node 10 and can confirm it is working

**Comment by Razzeee** [comment] 2020-04-26 13:52
Closing this, as I merged the branch.

**Closed by Razzeee** 2020-04-26 13:52 UTC

**Comment by Augustin82** [comment] 2020-04-26 14:13
For the record, I've experienced other instances of the problem, without being able to pinpoint it to anything. The CoC log remained empty. I don't have anything more meaningful to contribute, just thought I'd let you know.

Thanks a lot for the fix, in any case!

**Comment by Razzeee** [comment] 2020-04-26 15:02
Please let me know if your able to pinpoint it at some point.
