### ISSUE TITLE
Parsing files takes a long time

### ISSUE THREAD

**Issue by sporto** [elm-tooling/elm-language-server#138] opened 2019-08-01 22:59 UTC
When I save a file if formats sometimes, most of the time it fails.

I see the following in the output:

```
[2019-08-02 08:56:04.847] [renderer1] [warning] Aborted format on save after 750ms
[2019-08-02 08:56:34.569] [renderer1] [warning] Aborted format on save after 750ms
[2019-08-02 08:56:36.458] [renderer1] [warning] Aborted format on save after 750ms
[2019-08-02 08:56:47.032] [renderer1] [warning] Aborted format on save after 750ms
```

## Expected Behavior

Always format

## Current Behavior

Aborts formatting

## Steps to Reproduce (for bugs)

Save file

## Your Environment

* Version used: 0.4.2
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.36.1
* Environment name and version (e.g. node.js 5.4): 10.16.0
* Operating System and version: PopOS.

**Comment by Razzeee** [comment] 2019-08-18 23:47
I looked at why elm-format stagnates and it seems to be caused by the reference code lens to be "too expensive". I have an idea how to rewrite this.

**Comment by Razzeee** [comment] 2019-09-01 15:21
Trying to reproduce this to work on it. It seems like it's not happening in master anymore :/

**Comment by Razzeee** [comment] 2019-10-27 02:09
I will close this for now, feel free to reopen this with new infos.

**Closed by Razzeee** 2019-10-27 02:09 UTC
Labels: bug
