### ISSUE TITLE
Add setting for only showing diagnostics on save

### ISSUE THREAD

**Issue by alexander-js** [elm-tooling/elm-language-server#498] opened 2021-02-02 10:42 UTC
## Expected Behavior

I would like to be able to turn off the diagnostics that render as you type.

## Current Behavior

As of 2.0.0, diagnostics are rendered as you type (see gif)

## Possible Solution

Add a setting that enables users to turn off diagnostics when typing.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I find the diagnostic feedback while typing to be very distracting. Here is an example:

![Peek 2021-02-02 11-28](https://user-images.githubusercontent.com/28897531/106588000-9400d580-654a-11eb-97b8-9be893d4b3ee.gif)

This is especially distracting as I am using a plugin that makes errors and warnings more visible.
I would really appreciate to have the option to only be given diagnostics when I save.

## Your Environment

* Version used: 2.0.2
* Editor name and version (e.g. VSCode 1.36.1): Visual Studio Code 1.52.1
* Environment name and version (e.g. node.js 5.4): Node 12.16.2
* Operating System and version: Ubuntu 20.04.1

**Comment by jmbockhorst** [comment] 2021-02-02 12:30
Duplicate of #459.

**Closed by jmbockhorst** 2021-02-02 12:30 UTC
